server:
  port: 9090
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  zipkin:
    # zipkin服务器的地址
    base-url: http://localhost:9411
    # 关闭服务发现，否则springCloud会把zipkin的url当作服务名称
    discovery-client-enabled: false
    # 数据发送的方式：ACTIVEMQ RABBIT KAFKA WEB
    sender:
      type: web
    # 设置抽样采集率，默认0.1（即10%），这里设置为100%
    sleuth:
      sampler:
        probability: 1

myName:
  nacos-provider